/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame;


import org.transsonic.trustgame.data.trustgame.tables.Briefing;
import org.transsonic.trustgame.data.trustgame.tables.Carrier;
import org.transsonic.trustgame.data.trustgame.tables.Carrierreview;
import org.transsonic.trustgame.data.trustgame.tables.Client;
import org.transsonic.trustgame.data.trustgame.tables.Fbreport;
import org.transsonic.trustgame.data.trustgame.tables.Game;
import org.transsonic.trustgame.data.trustgame.tables.Gameplay;
import org.transsonic.trustgame.data.trustgame.tables.Gameuser;
import org.transsonic.trustgame.data.trustgame.tables.Mission;
import org.transsonic.trustgame.data.trustgame.tables.Order;
import org.transsonic.trustgame.data.trustgame.tables.Ordercarrier;
import org.transsonic.trustgame.data.trustgame.tables.Review;
import org.transsonic.trustgame.data.trustgame.tables.Round;
import org.transsonic.trustgame.data.trustgame.tables.Selectedcarrier;
import org.transsonic.trustgame.data.trustgame.tables.User;
import org.transsonic.trustgame.data.trustgame.tables.Usercarrier;
import org.transsonic.trustgame.data.trustgame.tables.Userclick;
import org.transsonic.trustgame.data.trustgame.tables.Usergroup;
import org.transsonic.trustgame.data.trustgame.tables.Userorder;
import org.transsonic.trustgame.data.trustgame.tables.Userround;


/**
 * Convenience access to all tables in trustgame.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>trustgame.briefing</code>.
     */
    public static final Briefing BRIEFING = Briefing.BRIEFING;

    /**
     * The table <code>trustgame.carrier</code>.
     */
    public static final Carrier CARRIER = Carrier.CARRIER;

    /**
     * The table <code>trustgame.carrierreview</code>.
     */
    public static final Carrierreview CARRIERREVIEW = Carrierreview.CARRIERREVIEW;

    /**
     * The table <code>trustgame.client</code>.
     */
    public static final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>trustgame.fbreport</code>.
     */
    public static final Fbreport FBREPORT = Fbreport.FBREPORT;

    /**
     * The table <code>trustgame.game</code>.
     */
    public static final Game GAME = Game.GAME;

    /**
     * The table <code>trustgame.gameplay</code>.
     */
    public static final Gameplay GAMEPLAY = Gameplay.GAMEPLAY;

    /**
     * The table <code>trustgame.gameuser</code>.
     */
    public static final Gameuser GAMEUSER = Gameuser.GAMEUSER;

    /**
     * The table <code>trustgame.mission</code>.
     */
    public static final Mission MISSION = Mission.MISSION;

    /**
     * The table <code>trustgame.order</code>.
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * The table <code>trustgame.ordercarrier</code>.
     */
    public static final Ordercarrier ORDERCARRIER = Ordercarrier.ORDERCARRIER;

    /**
     * The table <code>trustgame.review</code>.
     */
    public static final Review REVIEW = Review.REVIEW;

    /**
     * The table <code>trustgame.round</code>.
     */
    public static final Round ROUND = Round.ROUND;

    /**
     * The table <code>trustgame.selectedcarrier</code>.
     */
    public static final Selectedcarrier SELECTEDCARRIER = Selectedcarrier.SELECTEDCARRIER;

    /**
     * The table <code>trustgame.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>trustgame.usercarrier</code>.
     */
    public static final Usercarrier USERCARRIER = Usercarrier.USERCARRIER;

    /**
     * The table <code>trustgame.userclick</code>.
     */
    public static final Userclick USERCLICK = Userclick.USERCLICK;

    /**
     * The table <code>trustgame.usergroup</code>.
     */
    public static final Usergroup USERGROUP = Usergroup.USERGROUP;

    /**
     * The table <code>trustgame.userorder</code>.
     */
    public static final Userorder USERORDER = Userorder.USERORDER;

    /**
     * The table <code>trustgame.userround</code>.
     */
    public static final Userround USERROUND = Userround.USERROUND;
}
