/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Client;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientRecord extends UpdatableRecordImpl<ClientRecord> implements Record5<Integer, Integer, String, byte[], String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.client.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.client.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.client.Game_ID</code>.
     */
    public void setGameId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.client.Game_ID</code>.
     */
    public Integer getGameId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.client.Name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.client.Name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustgame.client.Logo</code>.
     */
    public void setLogo(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.client.Logo</code>.
     */
    public byte[] getLogo() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>trustgame.client.Type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.client.Type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, byte[], String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, byte[], String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Client.CLIENT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Client.CLIENT.GAME_ID;
    }

    @Override
    public Field<String> field3() {
        return Client.CLIENT.NAME;
    }

    @Override
    public Field<byte[]> field4() {
        return Client.CLIENT.LOGO;
    }

    @Override
    public Field<String> field5() {
        return Client.CLIENT.TYPE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getGameId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public byte[] component4() {
        return getLogo();
    }

    @Override
    public String component5() {
        return getType();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getGameId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public byte[] value4() {
        return getLogo();
    }

    @Override
    public String value5() {
        return getType();
    }

    @Override
    public ClientRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ClientRecord value2(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public ClientRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ClientRecord value4(byte[] value) {
        setLogo(value);
        return this;
    }

    @Override
    public ClientRecord value5(String value) {
        setType(value);
        return this;
    }

    @Override
    public ClientRecord values(Integer value1, Integer value2, String value3, byte[] value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRecord
     */
    public ClientRecord() {
        super(Client.CLIENT);
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(Integer id, Integer gameId, String name, byte[] logo, String type) {
        super(Client.CLIENT);

        setId(id);
        setGameId(gameId);
        setName(name);
        setLogo(logo);
        setType(type);
    }
}
