/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.transsonic.trustgame.data.trustgame.tables.Fbreport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FbreportRecord extends UpdatableRecordImpl<FbreportRecord> implements Record10<Integer, Integer, String, String, String, UInteger, byte[], byte[], byte[], byte[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.fbreport.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.fbreport.Carrier_ID</code>.
     */
    public void setCarrierId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.Carrier_ID</code>.
     */
    public Integer getCarrierId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.fbreport.FBRegistration</code>.
     */
    public void setFbregistration(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.FBRegistration</code>.
     */
    public String getFbregistration() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustgame.fbreport.CountryCode</code>.
     */
    public void setCountrycode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.CountryCode</code>.
     */
    public String getCountrycode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trustgame.fbreport.Address</code>.
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.Address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trustgame.fbreport.FBMemberSince</code>.
     */
    public void setFbmembersince(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.FBMemberSince</code>.
     */
    public UInteger getFbmembersince() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>trustgame.fbreport.ServiceOntime</code>.
     */
    public void setServiceontime(byte[] value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.ServiceOntime</code>.
     */
    public byte[] getServiceontime() {
        return (byte[]) get(6);
    }

    /**
     * Setter for <code>trustgame.fbreport.ServiceSatisfaction</code>.
     */
    public void setServicesatisfaction(byte[] value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.ServiceSatisfaction</code>.
     */
    public byte[] getServicesatisfaction() {
        return (byte[]) get(7);
    }

    /**
     * Setter for <code>trustgame.fbreport.TechnicalFleet</code>.
     */
    public void setTechnicalfleet(byte[] value) {
        set(8, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.TechnicalFleet</code>.
     */
    public byte[] getTechnicalfleet() {
        return (byte[]) get(8);
    }

    /**
     * Setter for <code>trustgame.fbreport.TechnicalGreen</code>.
     */
    public void setTechnicalgreen(byte[] value) {
        set(9, value);
    }

    /**
     * Getter for <code>trustgame.fbreport.TechnicalGreen</code>.
     */
    public byte[] getTechnicalgreen() {
        return (byte[]) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, String, String, String, UInteger, byte[], byte[], byte[], byte[]> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, String, String, String, UInteger, byte[], byte[], byte[], byte[]> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Fbreport.FBREPORT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Fbreport.FBREPORT.CARRIER_ID;
    }

    @Override
    public Field<String> field3() {
        return Fbreport.FBREPORT.FBREGISTRATION;
    }

    @Override
    public Field<String> field4() {
        return Fbreport.FBREPORT.COUNTRYCODE;
    }

    @Override
    public Field<String> field5() {
        return Fbreport.FBREPORT.ADDRESS;
    }

    @Override
    public Field<UInteger> field6() {
        return Fbreport.FBREPORT.FBMEMBERSINCE;
    }

    @Override
    public Field<byte[]> field7() {
        return Fbreport.FBREPORT.SERVICEONTIME;
    }

    @Override
    public Field<byte[]> field8() {
        return Fbreport.FBREPORT.SERVICESATISFACTION;
    }

    @Override
    public Field<byte[]> field9() {
        return Fbreport.FBREPORT.TECHNICALFLEET;
    }

    @Override
    public Field<byte[]> field10() {
        return Fbreport.FBREPORT.TECHNICALGREEN;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCarrierId();
    }

    @Override
    public String component3() {
        return getFbregistration();
    }

    @Override
    public String component4() {
        return getCountrycode();
    }

    @Override
    public String component5() {
        return getAddress();
    }

    @Override
    public UInteger component6() {
        return getFbmembersince();
    }

    @Override
    public byte[] component7() {
        return getServiceontime();
    }

    @Override
    public byte[] component8() {
        return getServicesatisfaction();
    }

    @Override
    public byte[] component9() {
        return getTechnicalfleet();
    }

    @Override
    public byte[] component10() {
        return getTechnicalgreen();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCarrierId();
    }

    @Override
    public String value3() {
        return getFbregistration();
    }

    @Override
    public String value4() {
        return getCountrycode();
    }

    @Override
    public String value5() {
        return getAddress();
    }

    @Override
    public UInteger value6() {
        return getFbmembersince();
    }

    @Override
    public byte[] value7() {
        return getServiceontime();
    }

    @Override
    public byte[] value8() {
        return getServicesatisfaction();
    }

    @Override
    public byte[] value9() {
        return getTechnicalfleet();
    }

    @Override
    public byte[] value10() {
        return getTechnicalgreen();
    }

    @Override
    public FbreportRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FbreportRecord value2(Integer value) {
        setCarrierId(value);
        return this;
    }

    @Override
    public FbreportRecord value3(String value) {
        setFbregistration(value);
        return this;
    }

    @Override
    public FbreportRecord value4(String value) {
        setCountrycode(value);
        return this;
    }

    @Override
    public FbreportRecord value5(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public FbreportRecord value6(UInteger value) {
        setFbmembersince(value);
        return this;
    }

    @Override
    public FbreportRecord value7(byte[] value) {
        setServiceontime(value);
        return this;
    }

    @Override
    public FbreportRecord value8(byte[] value) {
        setServicesatisfaction(value);
        return this;
    }

    @Override
    public FbreportRecord value9(byte[] value) {
        setTechnicalfleet(value);
        return this;
    }

    @Override
    public FbreportRecord value10(byte[] value) {
        setTechnicalgreen(value);
        return this;
    }

    @Override
    public FbreportRecord values(Integer value1, Integer value2, String value3, String value4, String value5, UInteger value6, byte[] value7, byte[] value8, byte[] value9, byte[] value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FbreportRecord
     */
    public FbreportRecord() {
        super(Fbreport.FBREPORT);
    }

    /**
     * Create a detached, initialised FbreportRecord
     */
    public FbreportRecord(Integer id, Integer carrierId, String fbregistration, String countrycode, String address, UInteger fbmembersince, byte[] serviceontime, byte[] servicesatisfaction, byte[] technicalfleet, byte[] technicalgreen) {
        super(Fbreport.FBREPORT);

        setId(id);
        setCarrierId(carrierId);
        setFbregistration(fbregistration);
        setCountrycode(countrycode);
        setAddress(address);
        setFbmembersince(fbmembersince);
        setServiceontime(serviceontime);
        setServicesatisfaction(servicesatisfaction);
        setTechnicalfleet(technicalfleet);
        setTechnicalgreen(technicalgreen);
    }
}
