/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Gameplay;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameplayRecord extends UpdatableRecordImpl<GameplayRecord> implements Record14<Integer, Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer, Byte, String, String, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.gameplay.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.gameplay.Game_ID</code>.
     */
    public void setGameId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.Game_ID</code>.
     */
    public Integer getGameId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.gameplay.GroupDescription</code>.
     */
    public void setGroupdescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.GroupDescription</code>.
     */
    public String getGroupdescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustgame.gameplay.StartPlayDate</code>. NULL means no restrictions
     */
    public void setStartplaydate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.StartPlayDate</code>. NULL means no restrictions
     */
    public LocalDateTime getStartplaydate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>trustgame.gameplay.EndPlayDate</code>. NULL means no restrictions
     */
    public void setEndplaydate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.EndPlayDate</code>. NULL means no restrictions
     */
    public LocalDateTime getEndplaydate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>trustgame.gameplay.Briefing_ID</code>.
     */
    public void setBriefingId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.Briefing_ID</code>.
     */
    public Integer getBriefingId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>trustgame.gameplay.Debriefing_ID</code>.
     */
    public void setDebriefingId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.Debriefing_ID</code>.
     */
    public Integer getDebriefingId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>trustgame.gameplay.Help_ID</code>.
     */
    public void setHelpId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.Help_ID</code>.
     */
    public Integer getHelpId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>trustgame.gameplay.Autoregister</code>.
     */
    public void setAutoregister(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.Autoregister</code>.
     */
    public Byte getAutoregister() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>trustgame.gameplay.GroupPassword</code>.
     */
    public void setGrouppassword(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.GroupPassword</code>.
     */
    public String getGrouppassword() {
        return (String) get(9);
    }

    /**
     * Setter for <code>trustgame.gameplay.UsernamePrefix</code>.
     */
    public void setUsernameprefix(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.UsernamePrefix</code>.
     */
    public String getUsernameprefix() {
        return (String) get(10);
    }

    /**
     * Setter for <code>trustgame.gameplay.AutoregisterText</code>.
     */
    public void setAutoregistertext(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.AutoregisterText</code>.
     */
    public String getAutoregistertext() {
        return (String) get(11);
    }

    /**
     * Setter for <code>trustgame.gameplay.AutoregisterUserGroup_ID</code>.
     */
    public void setAutoregisterusergroupId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.AutoregisterUserGroup_ID</code>.
     */
    public Integer getAutoregisterusergroupId() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>trustgame.gameplay.AutoregisterLink</code>.
     */
    public void setAutoregisterlink(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.AutoregisterLink</code>.
     */
    public String getAutoregisterlink() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer, Byte, String, String, String, Integer, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer, Byte, String, String, String, Integer, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Gameplay.GAMEPLAY.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Gameplay.GAMEPLAY.GAME_ID;
    }

    @Override
    public Field<String> field3() {
        return Gameplay.GAMEPLAY.GROUPDESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Gameplay.GAMEPLAY.STARTPLAYDATE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Gameplay.GAMEPLAY.ENDPLAYDATE;
    }

    @Override
    public Field<Integer> field6() {
        return Gameplay.GAMEPLAY.BRIEFING_ID;
    }

    @Override
    public Field<Integer> field7() {
        return Gameplay.GAMEPLAY.DEBRIEFING_ID;
    }

    @Override
    public Field<Integer> field8() {
        return Gameplay.GAMEPLAY.HELP_ID;
    }

    @Override
    public Field<Byte> field9() {
        return Gameplay.GAMEPLAY.AUTOREGISTER;
    }

    @Override
    public Field<String> field10() {
        return Gameplay.GAMEPLAY.GROUPPASSWORD;
    }

    @Override
    public Field<String> field11() {
        return Gameplay.GAMEPLAY.USERNAMEPREFIX;
    }

    @Override
    public Field<String> field12() {
        return Gameplay.GAMEPLAY.AUTOREGISTERTEXT;
    }

    @Override
    public Field<Integer> field13() {
        return Gameplay.GAMEPLAY.AUTOREGISTERUSERGROUP_ID;
    }

    @Override
    public Field<String> field14() {
        return Gameplay.GAMEPLAY.AUTOREGISTERLINK;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getGameId();
    }

    @Override
    public String component3() {
        return getGroupdescription();
    }

    @Override
    public LocalDateTime component4() {
        return getStartplaydate();
    }

    @Override
    public LocalDateTime component5() {
        return getEndplaydate();
    }

    @Override
    public Integer component6() {
        return getBriefingId();
    }

    @Override
    public Integer component7() {
        return getDebriefingId();
    }

    @Override
    public Integer component8() {
        return getHelpId();
    }

    @Override
    public Byte component9() {
        return getAutoregister();
    }

    @Override
    public String component10() {
        return getGrouppassword();
    }

    @Override
    public String component11() {
        return getUsernameprefix();
    }

    @Override
    public String component12() {
        return getAutoregistertext();
    }

    @Override
    public Integer component13() {
        return getAutoregisterusergroupId();
    }

    @Override
    public String component14() {
        return getAutoregisterlink();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getGameId();
    }

    @Override
    public String value3() {
        return getGroupdescription();
    }

    @Override
    public LocalDateTime value4() {
        return getStartplaydate();
    }

    @Override
    public LocalDateTime value5() {
        return getEndplaydate();
    }

    @Override
    public Integer value6() {
        return getBriefingId();
    }

    @Override
    public Integer value7() {
        return getDebriefingId();
    }

    @Override
    public Integer value8() {
        return getHelpId();
    }

    @Override
    public Byte value9() {
        return getAutoregister();
    }

    @Override
    public String value10() {
        return getGrouppassword();
    }

    @Override
    public String value11() {
        return getUsernameprefix();
    }

    @Override
    public String value12() {
        return getAutoregistertext();
    }

    @Override
    public Integer value13() {
        return getAutoregisterusergroupId();
    }

    @Override
    public String value14() {
        return getAutoregisterlink();
    }

    @Override
    public GameplayRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GameplayRecord value2(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public GameplayRecord value3(String value) {
        setGroupdescription(value);
        return this;
    }

    @Override
    public GameplayRecord value4(LocalDateTime value) {
        setStartplaydate(value);
        return this;
    }

    @Override
    public GameplayRecord value5(LocalDateTime value) {
        setEndplaydate(value);
        return this;
    }

    @Override
    public GameplayRecord value6(Integer value) {
        setBriefingId(value);
        return this;
    }

    @Override
    public GameplayRecord value7(Integer value) {
        setDebriefingId(value);
        return this;
    }

    @Override
    public GameplayRecord value8(Integer value) {
        setHelpId(value);
        return this;
    }

    @Override
    public GameplayRecord value9(Byte value) {
        setAutoregister(value);
        return this;
    }

    @Override
    public GameplayRecord value10(String value) {
        setGrouppassword(value);
        return this;
    }

    @Override
    public GameplayRecord value11(String value) {
        setUsernameprefix(value);
        return this;
    }

    @Override
    public GameplayRecord value12(String value) {
        setAutoregistertext(value);
        return this;
    }

    @Override
    public GameplayRecord value13(Integer value) {
        setAutoregisterusergroupId(value);
        return this;
    }

    @Override
    public GameplayRecord value14(String value) {
        setAutoregisterlink(value);
        return this;
    }

    @Override
    public GameplayRecord values(Integer value1, Integer value2, String value3, LocalDateTime value4, LocalDateTime value5, Integer value6, Integer value7, Integer value8, Byte value9, String value10, String value11, String value12, Integer value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameplayRecord
     */
    public GameplayRecord() {
        super(Gameplay.GAMEPLAY);
    }

    /**
     * Create a detached, initialised GameplayRecord
     */
    public GameplayRecord(Integer id, Integer gameId, String groupdescription, LocalDateTime startplaydate, LocalDateTime endplaydate, Integer briefingId, Integer debriefingId, Integer helpId, Byte autoregister, String grouppassword, String usernameprefix, String autoregistertext, Integer autoregisterusergroupId, String autoregisterlink) {
        super(Gameplay.GAMEPLAY);

        setId(id);
        setGameId(gameId);
        setGroupdescription(groupdescription);
        setStartplaydate(startplaydate);
        setEndplaydate(endplaydate);
        setBriefingId(briefingId);
        setDebriefingId(debriefingId);
        setHelpId(helpId);
        setAutoregister(autoregister);
        setGrouppassword(grouppassword);
        setUsernameprefix(usernameprefix);
        setAutoregistertext(autoregistertext);
        setAutoregisterusergroupId(autoregisterusergroupId);
        setAutoregisterlink(autoregisterlink);
    }
}
