/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Mission;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MissionRecord extends UpdatableRecordImpl<MissionRecord> implements Record13<Integer, Integer, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.mission.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.mission.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.mission.Game_ID</code>.
     */
    public void setGameId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.mission.Game_ID</code>.
     */
    public Integer getGameId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.mission.Name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.mission.Name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustgame.mission.Description</code>. HTML or Markdown
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.mission.Description</code>. HTML or Markdown
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trustgame.mission.TargetProfit</code>. Target line of the score chart
     */
    public void setTargetprofit(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.mission.TargetProfit</code>. Target line of the score chart
     */
    public Integer getTargetprofit() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>trustgame.mission.TargetSatisfaction</code>. Target line of the score chart
     */
    public void setTargetsatisfaction(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.mission.TargetSatisfaction</code>. Target line of the score chart
     */
    public Integer getTargetsatisfaction() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>trustgame.mission.TargetSustainability</code>. Target line of the score chart
     */
    public void setTargetsustainability(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustgame.mission.TargetSustainability</code>. Target line of the score chart
     */
    public Integer getTargetsustainability() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>trustgame.mission.StartProfit</code>. Start score of profit for a player
     */
    public void setStartprofit(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustgame.mission.StartProfit</code>. Start score of profit for a player
     */
    public Integer getStartprofit() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>trustgame.mission.StartSatisfaction</code>. Start score of satisfaction for a player
     */
    public void setStartsatisfaction(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>trustgame.mission.StartSatisfaction</code>. Start score of satisfaction for a player
     */
    public Integer getStartsatisfaction() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>trustgame.mission.StartSustainability</code>. Start score of sustainability for a player
     */
    public void setStartsustainability(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>trustgame.mission.StartSustainability</code>. Start score of sustainability for a player
     */
    public Integer getStartsustainability() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>trustgame.mission.MaxProfit</code>. Top of the score chart
     */
    public void setMaxprofit(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>trustgame.mission.MaxProfit</code>. Top of the score chart
     */
    public Integer getMaxprofit() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>trustgame.mission.MaxSatisfaction</code>. Top of the score chart
     */
    public void setMaxsatisfaction(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>trustgame.mission.MaxSatisfaction</code>. Top of the score chart
     */
    public Integer getMaxsatisfaction() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>trustgame.mission.MaxSustainability</code>. Top of the score chart
     */
    public void setMaxsustainability(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>trustgame.mission.MaxSustainability</code>. Top of the score chart
     */
    public Integer getMaxsustainability() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, Integer, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, Integer, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Mission.MISSION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Mission.MISSION.GAME_ID;
    }

    @Override
    public Field<String> field3() {
        return Mission.MISSION.NAME;
    }

    @Override
    public Field<String> field4() {
        return Mission.MISSION.DESCRIPTION;
    }

    @Override
    public Field<Integer> field5() {
        return Mission.MISSION.TARGETPROFIT;
    }

    @Override
    public Field<Integer> field6() {
        return Mission.MISSION.TARGETSATISFACTION;
    }

    @Override
    public Field<Integer> field7() {
        return Mission.MISSION.TARGETSUSTAINABILITY;
    }

    @Override
    public Field<Integer> field8() {
        return Mission.MISSION.STARTPROFIT;
    }

    @Override
    public Field<Integer> field9() {
        return Mission.MISSION.STARTSATISFACTION;
    }

    @Override
    public Field<Integer> field10() {
        return Mission.MISSION.STARTSUSTAINABILITY;
    }

    @Override
    public Field<Integer> field11() {
        return Mission.MISSION.MAXPROFIT;
    }

    @Override
    public Field<Integer> field12() {
        return Mission.MISSION.MAXSATISFACTION;
    }

    @Override
    public Field<Integer> field13() {
        return Mission.MISSION.MAXSUSTAINABILITY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getGameId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Integer component5() {
        return getTargetprofit();
    }

    @Override
    public Integer component6() {
        return getTargetsatisfaction();
    }

    @Override
    public Integer component7() {
        return getTargetsustainability();
    }

    @Override
    public Integer component8() {
        return getStartprofit();
    }

    @Override
    public Integer component9() {
        return getStartsatisfaction();
    }

    @Override
    public Integer component10() {
        return getStartsustainability();
    }

    @Override
    public Integer component11() {
        return getMaxprofit();
    }

    @Override
    public Integer component12() {
        return getMaxsatisfaction();
    }

    @Override
    public Integer component13() {
        return getMaxsustainability();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getGameId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public Integer value5() {
        return getTargetprofit();
    }

    @Override
    public Integer value6() {
        return getTargetsatisfaction();
    }

    @Override
    public Integer value7() {
        return getTargetsustainability();
    }

    @Override
    public Integer value8() {
        return getStartprofit();
    }

    @Override
    public Integer value9() {
        return getStartsatisfaction();
    }

    @Override
    public Integer value10() {
        return getStartsustainability();
    }

    @Override
    public Integer value11() {
        return getMaxprofit();
    }

    @Override
    public Integer value12() {
        return getMaxsatisfaction();
    }

    @Override
    public Integer value13() {
        return getMaxsustainability();
    }

    @Override
    public MissionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MissionRecord value2(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public MissionRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public MissionRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public MissionRecord value5(Integer value) {
        setTargetprofit(value);
        return this;
    }

    @Override
    public MissionRecord value6(Integer value) {
        setTargetsatisfaction(value);
        return this;
    }

    @Override
    public MissionRecord value7(Integer value) {
        setTargetsustainability(value);
        return this;
    }

    @Override
    public MissionRecord value8(Integer value) {
        setStartprofit(value);
        return this;
    }

    @Override
    public MissionRecord value9(Integer value) {
        setStartsatisfaction(value);
        return this;
    }

    @Override
    public MissionRecord value10(Integer value) {
        setStartsustainability(value);
        return this;
    }

    @Override
    public MissionRecord value11(Integer value) {
        setMaxprofit(value);
        return this;
    }

    @Override
    public MissionRecord value12(Integer value) {
        setMaxsatisfaction(value);
        return this;
    }

    @Override
    public MissionRecord value13(Integer value) {
        setMaxsustainability(value);
        return this;
    }

    @Override
    public MissionRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, Integer value11, Integer value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MissionRecord
     */
    public MissionRecord() {
        super(Mission.MISSION);
    }

    /**
     * Create a detached, initialised MissionRecord
     */
    public MissionRecord(Integer id, Integer gameId, String name, String description, Integer targetprofit, Integer targetsatisfaction, Integer targetsustainability, Integer startprofit, Integer startsatisfaction, Integer startsustainability, Integer maxprofit, Integer maxsatisfaction, Integer maxsustainability) {
        super(Mission.MISSION);

        setId(id);
        setGameId(gameId);
        setName(name);
        setDescription(description);
        setTargetprofit(targetprofit);
        setTargetsatisfaction(targetsatisfaction);
        setTargetsustainability(targetsustainability);
        setStartprofit(startprofit);
        setStartsatisfaction(startsatisfaction);
        setStartsustainability(startsustainability);
        setMaxprofit(maxprofit);
        setMaxsatisfaction(maxsatisfaction);
        setMaxsustainability(maxsustainability);
    }
}
