/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Ordercarrier;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdercarrierRecord extends UpdatableRecordImpl<OrdercarrierRecord> implements Record9<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.ordercarrier.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.ordercarrier.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.ordercarrier.Order_ID</code>.
     */
    public void setOrderId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.ordercarrier.Order_ID</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.ordercarrier.Carrier_ID</code>.
     */
    public void setCarrierId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.ordercarrier.Carrier_ID</code>.
     */
    public Integer getCarrierId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>trustgame.ordercarrier.QuoteOffer</code>. Number between 1 and 10
     */
    public void setQuoteoffer(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.ordercarrier.QuoteOffer</code>. Number between 1 and 10
     */
    public Integer getQuoteoffer() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>trustgame.ordercarrier.ExtraProfit</code>.
     */
    public void setExtraprofit(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.ordercarrier.ExtraProfit</code>.
     */
    public Integer getExtraprofit() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>trustgame.ordercarrier.OutcomeSustainability</code>.
     */
    public void setOutcomesustainability(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.ordercarrier.OutcomeSustainability</code>.
     */
    public Integer getOutcomesustainability() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>trustgame.ordercarrier.OutcomeSatisfaction</code>.
     */
    public void setOutcomesatisfaction(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustgame.ordercarrier.OutcomeSatisfaction</code>.
     */
    public Integer getOutcomesatisfaction() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>trustgame.ordercarrier.OutcomeMessage</code>.
     */
    public void setOutcomemessage(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustgame.ordercarrier.OutcomeMessage</code>.
     */
    public String getOutcomemessage() {
        return (String) get(7);
    }

    /**
     * Setter for <code>trustgame.ordercarrier.TransportMessage</code>.
     */
    public void setTransportmessage(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>trustgame.ordercarrier.TransportMessage</code>.
     */
    public String getTransportmessage() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Ordercarrier.ORDERCARRIER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Ordercarrier.ORDERCARRIER.ORDER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Ordercarrier.ORDERCARRIER.CARRIER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Ordercarrier.ORDERCARRIER.QUOTEOFFER;
    }

    @Override
    public Field<Integer> field5() {
        return Ordercarrier.ORDERCARRIER.EXTRAPROFIT;
    }

    @Override
    public Field<Integer> field6() {
        return Ordercarrier.ORDERCARRIER.OUTCOMESUSTAINABILITY;
    }

    @Override
    public Field<Integer> field7() {
        return Ordercarrier.ORDERCARRIER.OUTCOMESATISFACTION;
    }

    @Override
    public Field<String> field8() {
        return Ordercarrier.ORDERCARRIER.OUTCOMEMESSAGE;
    }

    @Override
    public Field<String> field9() {
        return Ordercarrier.ORDERCARRIER.TRANSPORTMESSAGE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getOrderId();
    }

    @Override
    public Integer component3() {
        return getCarrierId();
    }

    @Override
    public Integer component4() {
        return getQuoteoffer();
    }

    @Override
    public Integer component5() {
        return getExtraprofit();
    }

    @Override
    public Integer component6() {
        return getOutcomesustainability();
    }

    @Override
    public Integer component7() {
        return getOutcomesatisfaction();
    }

    @Override
    public String component8() {
        return getOutcomemessage();
    }

    @Override
    public String component9() {
        return getTransportmessage();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getOrderId();
    }

    @Override
    public Integer value3() {
        return getCarrierId();
    }

    @Override
    public Integer value4() {
        return getQuoteoffer();
    }

    @Override
    public Integer value5() {
        return getExtraprofit();
    }

    @Override
    public Integer value6() {
        return getOutcomesustainability();
    }

    @Override
    public Integer value7() {
        return getOutcomesatisfaction();
    }

    @Override
    public String value8() {
        return getOutcomemessage();
    }

    @Override
    public String value9() {
        return getTransportmessage();
    }

    @Override
    public OrdercarrierRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrdercarrierRecord value2(Integer value) {
        setOrderId(value);
        return this;
    }

    @Override
    public OrdercarrierRecord value3(Integer value) {
        setCarrierId(value);
        return this;
    }

    @Override
    public OrdercarrierRecord value4(Integer value) {
        setQuoteoffer(value);
        return this;
    }

    @Override
    public OrdercarrierRecord value5(Integer value) {
        setExtraprofit(value);
        return this;
    }

    @Override
    public OrdercarrierRecord value6(Integer value) {
        setOutcomesustainability(value);
        return this;
    }

    @Override
    public OrdercarrierRecord value7(Integer value) {
        setOutcomesatisfaction(value);
        return this;
    }

    @Override
    public OrdercarrierRecord value8(String value) {
        setOutcomemessage(value);
        return this;
    }

    @Override
    public OrdercarrierRecord value9(String value) {
        setTransportmessage(value);
        return this;
    }

    @Override
    public OrdercarrierRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdercarrierRecord
     */
    public OrdercarrierRecord() {
        super(Ordercarrier.ORDERCARRIER);
    }

    /**
     * Create a detached, initialised OrdercarrierRecord
     */
    public OrdercarrierRecord(Integer id, Integer orderId, Integer carrierId, Integer quoteoffer, Integer extraprofit, Integer outcomesustainability, Integer outcomesatisfaction, String outcomemessage, String transportmessage) {
        super(Ordercarrier.ORDERCARRIER);

        setId(id);
        setOrderId(orderId);
        setCarrierId(carrierId);
        setQuoteoffer(quoteoffer);
        setExtraprofit(extraprofit);
        setOutcomesustainability(outcomesustainability);
        setOutcomesatisfaction(outcomesatisfaction);
        setOutcomemessage(outcomemessage);
        setTransportmessage(transportmessage);
    }
}
