/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Review;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReviewRecord extends UpdatableRecordImpl<ReviewRecord> implements Record6<Integer, Integer, Integer, Double, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.review.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.review.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.review.Round_ID</code>.
     */
    public void setRoundId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.review.Round_ID</code>.
     */
    public Integer getRoundId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.review.Carrier_ID</code>.
     */
    public void setCarrierId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.review.Carrier_ID</code>.
     */
    public Integer getCarrierId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>trustgame.review.Stars</code>.
     */
    public void setStars(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.review.Stars</code>.
     */
    public Double getStars() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>trustgame.review.When</code>.
     */
    public void setWhen(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.review.When</code>.
     */
    public String getWhen() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trustgame.review.ReviewText</code>.
     */
    public void setReviewtext(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.review.ReviewText</code>.
     */
    public String getReviewtext() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, Double, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, Double, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Review.REVIEW.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Review.REVIEW.ROUND_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Review.REVIEW.CARRIER_ID;
    }

    @Override
    public Field<Double> field4() {
        return Review.REVIEW.STARS;
    }

    @Override
    public Field<String> field5() {
        return Review.REVIEW.WHEN;
    }

    @Override
    public Field<String> field6() {
        return Review.REVIEW.REVIEWTEXT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getRoundId();
    }

    @Override
    public Integer component3() {
        return getCarrierId();
    }

    @Override
    public Double component4() {
        return getStars();
    }

    @Override
    public String component5() {
        return getWhen();
    }

    @Override
    public String component6() {
        return getReviewtext();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getRoundId();
    }

    @Override
    public Integer value3() {
        return getCarrierId();
    }

    @Override
    public Double value4() {
        return getStars();
    }

    @Override
    public String value5() {
        return getWhen();
    }

    @Override
    public String value6() {
        return getReviewtext();
    }

    @Override
    public ReviewRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ReviewRecord value2(Integer value) {
        setRoundId(value);
        return this;
    }

    @Override
    public ReviewRecord value3(Integer value) {
        setCarrierId(value);
        return this;
    }

    @Override
    public ReviewRecord value4(Double value) {
        setStars(value);
        return this;
    }

    @Override
    public ReviewRecord value5(String value) {
        setWhen(value);
        return this;
    }

    @Override
    public ReviewRecord value6(String value) {
        setReviewtext(value);
        return this;
    }

    @Override
    public ReviewRecord values(Integer value1, Integer value2, Integer value3, Double value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReviewRecord
     */
    public ReviewRecord() {
        super(Review.REVIEW);
    }

    /**
     * Create a detached, initialised ReviewRecord
     */
    public ReviewRecord(Integer id, Integer roundId, Integer carrierId, Double stars, String when, String reviewtext) {
        super(Review.REVIEW);

        setId(id);
        setRoundId(roundId);
        setCarrierId(carrierId);
        setStars(stars);
        setWhen(when);
        setReviewtext(reviewtext);
    }
}
