/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.User;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record9<Integer, Integer, String, String, String, String, LocalDateTime, Byte, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.user.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.user.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.user.UserGroup_ID</code>.
     */
    public void setUsergroupId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.user.UserGroup_ID</code>.
     */
    public Integer getUsergroupId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.user.Username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.user.Username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustgame.user.Email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.user.Email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trustgame.user.Name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.user.Name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trustgame.user.Password</code>.
     */
    public void setPassword(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.user.Password</code>.
     */
    public String getPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>trustgame.user.CreateTime</code>.
     */
    public void setCreatetime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustgame.user.CreateTime</code>.
     */
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>trustgame.user.Administrator</code>.
     */
    public void setAdministrator(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustgame.user.Administrator</code>.
     */
    public Byte getAdministrator() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>trustgame.user.UserCode</code>.
     */
    public void setUsercode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>trustgame.user.UserCode</code>.
     */
    public String getUsercode() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, String, String, String, String, LocalDateTime, Byte, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, String, String, String, String, LocalDateTime, Byte, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return User.USER.USERGROUP_ID;
    }

    @Override
    public Field<String> field3() {
        return User.USER.USERNAME;
    }

    @Override
    public Field<String> field4() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return User.USER.NAME;
    }

    @Override
    public Field<String> field6() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return User.USER.CREATETIME;
    }

    @Override
    public Field<Byte> field8() {
        return User.USER.ADMINISTRATOR;
    }

    @Override
    public Field<String> field9() {
        return User.USER.USERCODE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUsergroupId();
    }

    @Override
    public String component3() {
        return getUsername();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public String component6() {
        return getPassword();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatetime();
    }

    @Override
    public Byte component8() {
        return getAdministrator();
    }

    @Override
    public String component9() {
        return getUsercode();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUsergroupId();
    }

    @Override
    public String value3() {
        return getUsername();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public String value6() {
        return getPassword();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatetime();
    }

    @Override
    public Byte value8() {
        return getAdministrator();
    }

    @Override
    public String value9() {
        return getUsercode();
    }

    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(Integer value) {
        setUsergroupId(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value7(LocalDateTime value) {
        setCreatetime(value);
        return this;
    }

    @Override
    public UserRecord value8(Byte value) {
        setAdministrator(value);
        return this;
    }

    @Override
    public UserRecord value9(String value) {
        setUsercode(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, LocalDateTime value7, Byte value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, Integer usergroupId, String username, String email, String name, String password, LocalDateTime createtime, Byte administrator, String usercode) {
        super(User.USER);

        setId(id);
        setUsergroupId(usergroupId);
        setUsername(username);
        setEmail(email);
        setName(name);
        setPassword(password);
        setCreatetime(createtime);
        setAdministrator(administrator);
        setUsercode(usercode);
    }
}
