/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum CarrierSustainability implements EnumType {

    Low("Low"),

    Medium("Medium"),

    High("High");

    private final String literal;

    private CarrierSustainability(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "carrier_Sustainability";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
