/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Carrierreview;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarrierreviewRecord extends UpdatableRecordImpl<CarrierreviewRecord> implements Record4<Integer, Integer, Integer, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.carrierreview.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.carrierreview.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.carrierreview.Round_ID</code>.
     */
    public void setRoundId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.carrierreview.Round_ID</code>.
     */
    public Integer getRoundId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.carrierreview.Carrier_ID</code>.
     */
    public void setCarrierId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.carrierreview.Carrier_ID</code>.
     */
    public Integer getCarrierId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>trustgame.carrierreview.OverallStars</code>. Whole of half numbers from 1.0 to 5.0
     */
    public void setOverallstars(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.carrierreview.OverallStars</code>. Whole of half numbers from 1.0 to 5.0
     */
    public Double getOverallstars() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Carrierreview.CARRIERREVIEW.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Carrierreview.CARRIERREVIEW.ROUND_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Carrierreview.CARRIERREVIEW.CARRIER_ID;
    }

    @Override
    public Field<Double> field4() {
        return Carrierreview.CARRIERREVIEW.OVERALLSTARS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getRoundId();
    }

    @Override
    public Integer component3() {
        return getCarrierId();
    }

    @Override
    public Double component4() {
        return getOverallstars();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getRoundId();
    }

    @Override
    public Integer value3() {
        return getCarrierId();
    }

    @Override
    public Double value4() {
        return getOverallstars();
    }

    @Override
    public CarrierreviewRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CarrierreviewRecord value2(Integer value) {
        setRoundId(value);
        return this;
    }

    @Override
    public CarrierreviewRecord value3(Integer value) {
        setCarrierId(value);
        return this;
    }

    @Override
    public CarrierreviewRecord value4(Double value) {
        setOverallstars(value);
        return this;
    }

    @Override
    public CarrierreviewRecord values(Integer value1, Integer value2, Integer value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarrierreviewRecord
     */
    public CarrierreviewRecord() {
        super(Carrierreview.CARRIERREVIEW);
    }

    /**
     * Create a detached, initialised CarrierreviewRecord
     */
    public CarrierreviewRecord(Integer id, Integer roundId, Integer carrierId, Double overallstars) {
        super(Carrierreview.CARRIERREVIEW);

        setId(id);
        setRoundId(roundId);
        setCarrierId(carrierId);
        setOverallstars(overallstars);
    }
}
