/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Gameplay;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameplayRecord extends UpdatableRecordImpl<GameplayRecord> implements Record8<Integer, Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.gameplay.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.gameplay.Game_ID</code>.
     */
    public void setGameId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.Game_ID</code>.
     */
    public Integer getGameId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.gameplay.GroupDescription</code>.
     */
    public void setGroupdescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.GroupDescription</code>.
     */
    public String getGroupdescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustgame.gameplay.StartPlayDate</code>. NULL means no restrictions
     */
    public void setStartplaydate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.StartPlayDate</code>. NULL means no restrictions
     */
    public LocalDateTime getStartplaydate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>trustgame.gameplay.EndPlayDate</code>. NULL means no restrictions
     */
    public void setEndplaydate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.EndPlayDate</code>. NULL means no restrictions
     */
    public LocalDateTime getEndplaydate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>trustgame.gameplay.Briefing_ID</code>.
     */
    public void setBriefingId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.Briefing_ID</code>.
     */
    public Integer getBriefingId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>trustgame.gameplay.Debriefing_ID</code>.
     */
    public void setDebriefingId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.Debriefing_ID</code>.
     */
    public Integer getDebriefingId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>trustgame.gameplay.Help_ID</code>.
     */
    public void setHelpId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustgame.gameplay.Help_ID</code>.
     */
    public Integer getHelpId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Gameplay.GAMEPLAY.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Gameplay.GAMEPLAY.GAME_ID;
    }

    @Override
    public Field<String> field3() {
        return Gameplay.GAMEPLAY.GROUPDESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Gameplay.GAMEPLAY.STARTPLAYDATE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Gameplay.GAMEPLAY.ENDPLAYDATE;
    }

    @Override
    public Field<Integer> field6() {
        return Gameplay.GAMEPLAY.BRIEFING_ID;
    }

    @Override
    public Field<Integer> field7() {
        return Gameplay.GAMEPLAY.DEBRIEFING_ID;
    }

    @Override
    public Field<Integer> field8() {
        return Gameplay.GAMEPLAY.HELP_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getGameId();
    }

    @Override
    public String component3() {
        return getGroupdescription();
    }

    @Override
    public LocalDateTime component4() {
        return getStartplaydate();
    }

    @Override
    public LocalDateTime component5() {
        return getEndplaydate();
    }

    @Override
    public Integer component6() {
        return getBriefingId();
    }

    @Override
    public Integer component7() {
        return getDebriefingId();
    }

    @Override
    public Integer component8() {
        return getHelpId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getGameId();
    }

    @Override
    public String value3() {
        return getGroupdescription();
    }

    @Override
    public LocalDateTime value4() {
        return getStartplaydate();
    }

    @Override
    public LocalDateTime value5() {
        return getEndplaydate();
    }

    @Override
    public Integer value6() {
        return getBriefingId();
    }

    @Override
    public Integer value7() {
        return getDebriefingId();
    }

    @Override
    public Integer value8() {
        return getHelpId();
    }

    @Override
    public GameplayRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GameplayRecord value2(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public GameplayRecord value3(String value) {
        setGroupdescription(value);
        return this;
    }

    @Override
    public GameplayRecord value4(LocalDateTime value) {
        setStartplaydate(value);
        return this;
    }

    @Override
    public GameplayRecord value5(LocalDateTime value) {
        setEndplaydate(value);
        return this;
    }

    @Override
    public GameplayRecord value6(Integer value) {
        setBriefingId(value);
        return this;
    }

    @Override
    public GameplayRecord value7(Integer value) {
        setDebriefingId(value);
        return this;
    }

    @Override
    public GameplayRecord value8(Integer value) {
        setHelpId(value);
        return this;
    }

    @Override
    public GameplayRecord values(Integer value1, Integer value2, String value3, LocalDateTime value4, LocalDateTime value5, Integer value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameplayRecord
     */
    public GameplayRecord() {
        super(Gameplay.GAMEPLAY);
    }

    /**
     * Create a detached, initialised GameplayRecord
     */
    public GameplayRecord(Integer id, Integer gameId, String groupdescription, LocalDateTime startplaydate, LocalDateTime endplaydate, Integer briefingId, Integer debriefingId, Integer helpId) {
        super(Gameplay.GAMEPLAY);

        setId(id);
        setGameId(gameId);
        setGroupdescription(groupdescription);
        setStartplaydate(startplaydate);
        setEndplaydate(endplaydate);
        setBriefingId(briefingId);
        setDebriefingId(debriefingId);
        setHelpId(helpId);
    }
}
