/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Game;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record7<Integer, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.game.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.game.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.game.Code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.game.Code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>trustgame.game.Name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.game.Name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trustgame.game.Description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.game.Description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trustgame.game.TextFinishDay</code>.
     */
    public void setTextfinishday(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.game.TextFinishDay</code>.
     */
    public String getTextfinishday() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trustgame.game.TextReview</code>.
     */
    public void setTextreview(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.game.TextReview</code>.
     */
    public String getTextreview() {
        return (String) get(5);
    }

    /**
     * Setter for <code>trustgame.game.TextAllReviews</code>.
     */
    public void setTextallreviews(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustgame.game.TextAllReviews</code>.
     */
    public String getTextallreviews() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Game.GAME.ID;
    }

    @Override
    public Field<String> field2() {
        return Game.GAME.CODE;
    }

    @Override
    public Field<String> field3() {
        return Game.GAME.NAME;
    }

    @Override
    public Field<String> field4() {
        return Game.GAME.DESCRIPTION;
    }

    @Override
    public Field<String> field5() {
        return Game.GAME.TEXTFINISHDAY;
    }

    @Override
    public Field<String> field6() {
        return Game.GAME.TEXTREVIEW;
    }

    @Override
    public Field<String> field7() {
        return Game.GAME.TEXTALLREVIEWS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String component5() {
        return getTextfinishday();
    }

    @Override
    public String component6() {
        return getTextreview();
    }

    @Override
    public String component7() {
        return getTextallreviews();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public String value5() {
        return getTextfinishday();
    }

    @Override
    public String value6() {
        return getTextreview();
    }

    @Override
    public String value7() {
        return getTextallreviews();
    }

    @Override
    public GameRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GameRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public GameRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public GameRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public GameRecord value5(String value) {
        setTextfinishday(value);
        return this;
    }

    @Override
    public GameRecord value6(String value) {
        setTextreview(value);
        return this;
    }

    @Override
    public GameRecord value7(String value) {
        setTextallreviews(value);
        return this;
    }

    @Override
    public GameRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(Integer id, String code, String name, String description, String textfinishday, String textreview, String textallreviews) {
        super(Game.GAME);

        setId(id);
        setCode(code);
        setName(name);
        setDescription(description);
        setTextfinishday(textfinishday);
        setTextreview(textreview);
        setTextallreviews(textallreviews);
    }
}
