/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Selectedcarrier;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectedcarrierRecord extends UpdatableRecordImpl<SelectedcarrierRecord> implements Record5<Integer, Integer, Integer, LocalDateTime, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.selectedcarrier.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.selectedcarrier.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.selectedcarrier.UserOrder_ID</code>.
     */
    public void setUserorderId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.selectedcarrier.UserOrder_ID</code>.
     */
    public Integer getUserorderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.selectedcarrier.OrderCarrier_ID</code>.
     */
    public void setOrdercarrierId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.selectedcarrier.OrderCarrier_ID</code>.
     */
    public Integer getOrdercarrierId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>trustgame.selectedcarrier.SelectionTime</code>.
     */
    public void setSelectiontime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.selectedcarrier.SelectionTime</code>.
     */
    public LocalDateTime getSelectiontime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>trustgame.selectedcarrier.UserScore</code>.
     */
    public void setUserscore(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.selectedcarrier.UserScore</code>.
     */
    public Double getUserscore() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Selectedcarrier.SELECTEDCARRIER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Selectedcarrier.SELECTEDCARRIER.USERORDER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Selectedcarrier.SELECTEDCARRIER.ORDERCARRIER_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Selectedcarrier.SELECTEDCARRIER.SELECTIONTIME;
    }

    @Override
    public Field<Double> field5() {
        return Selectedcarrier.SELECTEDCARRIER.USERSCORE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserorderId();
    }

    @Override
    public Integer component3() {
        return getOrdercarrierId();
    }

    @Override
    public LocalDateTime component4() {
        return getSelectiontime();
    }

    @Override
    public Double component5() {
        return getUserscore();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserorderId();
    }

    @Override
    public Integer value3() {
        return getOrdercarrierId();
    }

    @Override
    public LocalDateTime value4() {
        return getSelectiontime();
    }

    @Override
    public Double value5() {
        return getUserscore();
    }

    @Override
    public SelectedcarrierRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SelectedcarrierRecord value2(Integer value) {
        setUserorderId(value);
        return this;
    }

    @Override
    public SelectedcarrierRecord value3(Integer value) {
        setOrdercarrierId(value);
        return this;
    }

    @Override
    public SelectedcarrierRecord value4(LocalDateTime value) {
        setSelectiontime(value);
        return this;
    }

    @Override
    public SelectedcarrierRecord value5(Double value) {
        setUserscore(value);
        return this;
    }

    @Override
    public SelectedcarrierRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelectedcarrierRecord
     */
    public SelectedcarrierRecord() {
        super(Selectedcarrier.SELECTEDCARRIER);
    }

    /**
     * Create a detached, initialised SelectedcarrierRecord
     */
    public SelectedcarrierRecord(Integer id, Integer userorderId, Integer ordercarrierId, LocalDateTime selectiontime, Double userscore) {
        super(Selectedcarrier.SELECTEDCARRIER);

        setId(id);
        setUserorderId(userorderId);
        setOrdercarrierId(ordercarrierId);
        setSelectiontime(selectiontime);
        setUserscore(userscore);
    }
}
