/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Usergroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsergroupRecord extends UpdatableRecordImpl<UsergroupRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.usergroup.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.usergroup.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.usergroup.GroupName</code>.
     */
    public void setGroupname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.usergroup.GroupName</code>.
     */
    public String getGroupname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Usergroup.USERGROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return Usergroup.USERGROUP.GROUPNAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getGroupname();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getGroupname();
    }

    @Override
    public UsergroupRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UsergroupRecord value2(String value) {
        setGroupname(value);
        return this;
    }

    @Override
    public UsergroupRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsergroupRecord
     */
    public UsergroupRecord() {
        super(Usergroup.USERGROUP);
    }

    /**
     * Create a detached, initialised UsergroupRecord
     */
    public UsergroupRecord(Integer id, String groupname) {
        super(Usergroup.USERGROUP);

        setId(id);
        setGroupname(groupname);
    }
}
