/*
 * This file is generated by jOOQ.
 */
package org.transsonic.trustgame.data.trustgame.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.transsonic.trustgame.data.trustgame.tables.Userclick;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserclickRecord extends UpdatableRecordImpl<UserclickRecord> implements Record9<Integer, Integer, LocalDateTime, String, String, Integer, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trustgame.userclick.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trustgame.userclick.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trustgame.userclick.GameUser_ID</code>.
     */
    public void setGameuserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>trustgame.userclick.GameUser_ID</code>.
     */
    public Integer getGameuserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trustgame.userclick.Timestamp</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>trustgame.userclick.Timestamp</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>trustgame.userclick.ButtonOrField</code>. Name of the button or field where the user clicked. Not standardized in a table since the GUI can change.
     */
    public void setButtonorfield(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>trustgame.userclick.ButtonOrField</code>. Name of the button or field where the user clicked. Not standardized in a table since the GUI can change.
     */
    public String getButtonorfield() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trustgame.userclick.Value</code>. If a user could fill something out, the value is given here
     */
    public void setValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>trustgame.userclick.Value</code>. If a user could fill something out, the value is given here
     */
    public String getValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trustgame.userclick.RoundNumber</code>.
     */
    public void setRoundnumber(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>trustgame.userclick.RoundNumber</code>.
     */
    public Integer getRoundnumber() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>trustgame.userclick.OrderNumber</code>.
     */
    public void setOrdernumber(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>trustgame.userclick.OrderNumber</code>.
     */
    public Integer getOrdernumber() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>trustgame.userclick.ClientName</code>.
     */
    public void setClientname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>trustgame.userclick.ClientName</code>.
     */
    public String getClientname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>trustgame.userclick.CarrierName</code>.
     */
    public void setCarriername(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>trustgame.userclick.CarrierName</code>.
     */
    public String getCarriername() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, LocalDateTime, String, String, Integer, Integer, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, LocalDateTime, String, String, Integer, Integer, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Userclick.USERCLICK.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Userclick.USERCLICK.GAMEUSER_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Userclick.USERCLICK.TIMESTAMP;
    }

    @Override
    public Field<String> field4() {
        return Userclick.USERCLICK.BUTTONORFIELD;
    }

    @Override
    public Field<String> field5() {
        return Userclick.USERCLICK.VALUE;
    }

    @Override
    public Field<Integer> field6() {
        return Userclick.USERCLICK.ROUNDNUMBER;
    }

    @Override
    public Field<Integer> field7() {
        return Userclick.USERCLICK.ORDERNUMBER;
    }

    @Override
    public Field<String> field8() {
        return Userclick.USERCLICK.CLIENTNAME;
    }

    @Override
    public Field<String> field9() {
        return Userclick.USERCLICK.CARRIERNAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getGameuserId();
    }

    @Override
    public LocalDateTime component3() {
        return getTimestamp();
    }

    @Override
    public String component4() {
        return getButtonorfield();
    }

    @Override
    public String component5() {
        return getValue();
    }

    @Override
    public Integer component6() {
        return getRoundnumber();
    }

    @Override
    public Integer component7() {
        return getOrdernumber();
    }

    @Override
    public String component8() {
        return getClientname();
    }

    @Override
    public String component9() {
        return getCarriername();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getGameuserId();
    }

    @Override
    public LocalDateTime value3() {
        return getTimestamp();
    }

    @Override
    public String value4() {
        return getButtonorfield();
    }

    @Override
    public String value5() {
        return getValue();
    }

    @Override
    public Integer value6() {
        return getRoundnumber();
    }

    @Override
    public Integer value7() {
        return getOrdernumber();
    }

    @Override
    public String value8() {
        return getClientname();
    }

    @Override
    public String value9() {
        return getCarriername();
    }

    @Override
    public UserclickRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserclickRecord value2(Integer value) {
        setGameuserId(value);
        return this;
    }

    @Override
    public UserclickRecord value3(LocalDateTime value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public UserclickRecord value4(String value) {
        setButtonorfield(value);
        return this;
    }

    @Override
    public UserclickRecord value5(String value) {
        setValue(value);
        return this;
    }

    @Override
    public UserclickRecord value6(Integer value) {
        setRoundnumber(value);
        return this;
    }

    @Override
    public UserclickRecord value7(Integer value) {
        setOrdernumber(value);
        return this;
    }

    @Override
    public UserclickRecord value8(String value) {
        setClientname(value);
        return this;
    }

    @Override
    public UserclickRecord value9(String value) {
        setCarriername(value);
        return this;
    }

    @Override
    public UserclickRecord values(Integer value1, Integer value2, LocalDateTime value3, String value4, String value5, Integer value6, Integer value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserclickRecord
     */
    public UserclickRecord() {
        super(Userclick.USERCLICK);
    }

    /**
     * Create a detached, initialised UserclickRecord
     */
    public UserclickRecord(Integer id, Integer gameuserId, LocalDateTime timestamp, String buttonorfield, String value, Integer roundnumber, Integer ordernumber, String clientname, String carriername) {
        super(Userclick.USERCLICK);

        setId(id);
        setGameuserId(gameuserId);
        setTimestamp(timestamp);
        setButtonorfield(buttonorfield);
        setValue(value);
        setRoundnumber(roundnumber);
        setOrdernumber(ordernumber);
        setClientname(clientname);
        setCarriername(carriername);
    }
}
